begin;

create table if not exists public.site_analytics_events (
  id bigint generated by default as identity primary key,
  event_name text not null check (event_name ~ '^[a-z0-9_]{1,64}$'),
  path text not null check (char_length(path) between 1 and 300),
  visitor_id uuid not null,
  session_id uuid not null,
  user_id uuid references auth.users(id) on delete set null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.site_analytics_events enable row level security;

revoke all on table public.site_analytics_events from anon, authenticated;
revoke all on sequence public.site_analytics_events_id_seq from anon, authenticated;

create index if not exists site_analytics_events_created_at_idx
  on public.site_analytics_events (created_at desc);
create index if not exists site_analytics_events_event_created_idx
  on public.site_analytics_events (event_name, created_at desc);
create index if not exists site_analytics_events_path_created_idx
  on public.site_analytics_events (path, created_at desc);
create index if not exists site_analytics_events_visitor_created_idx
  on public.site_analytics_events (visitor_id, created_at desc);
create index if not exists site_analytics_events_user_created_idx
  on public.site_analytics_events (user_id, created_at desc)
  where user_id is not null;

comment on table public.site_analytics_events is
  'First-party Embers usage analytics. Stores random browser/session identifiers, route/event data, and authenticated user id when available. No email, IP address, payment data, or query strings are intentionally stored.';

commit;
